module Arrangements exposing (..)


stabalisingToRepeating : String
stabalisingToRepeating =
    """
    ...........
    .....*.....
    ......*....
    ....***....
    ...........
    ...........
    ....*......
    ....*......
    ....*......
    ...........
    ...........
    """


stabalisingToStatic : String
stabalisingToStatic =
    """
    ...........
    .....*.....
    ......*....
    ....***....
    ...........
    ..*........
    ....*......
    ....*......
    ....*......
    ...........
    ...........
    """
