name: TUYUL 2077
on: [push, pull_request]
jobs:
  build:
    name: Gaskan
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        go: [1.6, 1.7, 1.8, 1.9, 1.10, 1.11, 1.12, 1.13, 1.14, 1.15]
        flag: [A, B]
    timeout-minutes: 360
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: Gaskan
      run: |
        echo "1"
